# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Builder stage
FROM node:lts-alpine AS builder
WORKDIR /app

# Install dependencies including dev dependencies for build
COPY package.json tsconfig.json .
RUN npm install

# Copy source and build
COPY . .
RUN npm run build

# Runtime stage
FROM node:lts-alpine
WORKDIR /app

# Copy built files and runtime dependencies
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules

ENV NODE_ENV=production

CMD ["node", "dist/index.js"]
